name: sleap-hackathon

dependencies:
- python=3.6
- Pillow
- Shapely
- pip
- pip:
    - "--extra-index-url https://pypi.ngc.nvidia.com"
    - nvidia-pyindex  # redundant with the above?
    - "--editable=./"
    - "--requirement=./dev_requirements.txt"
